### ISSUE TITLE
Filter by Known Gear Type  and Inferred Gear Type (and other criteria in the future)

### ISSUE THREAD

**Issue by nerik** [Vizzuality/GlobalFishingWatch#661]
https://airtable.com/tbliFUBZhHrWTVy5I/viwjB6S36hfjUz7EU/rec1YXkuNv7bHcZgc

### Features

- [x] Add new "Filters" panel, with a list of filters https://github.com/vizzuality/globalfishingwatch/issues/706
- [x] Implement "filter group" modal, with options to config color, name and such https://github.com/vizzuality/globalfishingwatch/issues/707
- [x] "Filter group" logic changes https://github.com/vizzuality/globalfishingwatch/issues/730

Added after planning
- [x] Filters description https://github.com/Vizzuality/GlobalFishingWatch/issues/805
- [x] Clarify filter group modal https://github.com/Vizzuality/GlobalFishingWatch/issues/804
- [ ] API should indicate available flags https://github.com/Vizzuality/GlobalFishingWatch/issues/813
- [x] Implement changed reports API (flags only) https://github.com/Vizzuality/GlobalFishingWatch/issues/833

### Bugs

- [ ] Horizontal scrollbar is being displayed on the filters section of the menu https://github.com/Vizzuality/GlobalFishingWatch/issues/806
- [x] broken styles when layer name is long https://github.com/Vizzuality/GlobalFishingWatch/issues/807
- [x] When you select two filters, you lose the ability to select vessels https://github.com/Vizzuality/GlobalFishingWatch/issues/808
- [x] Highlight layer not filtered out enough when more than 1 filter group https://github.com/Vizzuality/GlobalFishingWatch/issues/812
- [x] Put back landlocked countries https://github.com/Vizzuality/GlobalFishingWatch/issues/814

### To test
- [x] reports
- [ ] analytics

**Comment by nerik** [comment]
@enriquetuya 
We're having a doubt about an certain edge case on filtering:
If you apply a gear type filter to a AIS layer (so that doesn't have any gear type info)
Should we display *none* of the vessels or *all* of the vessels (ie just bypass the filter)?

We already implemented not showing the gear type filter selector when a layer does not support it.
But, in the particular case where the workspace also contains a layer where gear type is available (ie you have a VMS and an AIS layer), the user can apply a gear type filter to both layers.

It seems logical in that case to hide the entirety of the AIS filter, but we wanted to make sure of this with you.

Thanks.

**Comment by enriquetuya** [comment]
@nerik hiding the entirety of the AIS filter seems to be a good approach for the first version of the filters. If doing so doesn't mean to add to much extra work, proceed.

**Comment by nerik** [comment]
@enriquetuya Thanks, will do.

**Comment by nerik** [comment]
@enriquetuya Hi, two more questions about filters:
1. are all tilesets, including legacy ones, now including `filters` in their headers? Currently we have some support for layers headers without filters, but it was not intended to last.
2. would you be able to produce tilesets (including legacy ones) that have their `category` field for each point replaced by a `flag_id` field ? The problem is that supporting both, on the client side leads to some complex branching (as they appear unified in the UI even though they are distinct fields).

**Comment by nerik** [comment]
(about 2., I just noticed there's an `id` field on headers' filters that resolves to `flag` in both cases, so we should probably use that)

**Comment by nerik** [comment]
Issues have been created from this initial document: https://docs.google.com/document/d/1WgxGq7yuybnDa9Y2N2lma1MqQerUdi2Pur6INxMHYQM/edit
